name: Build, Test and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake rpm

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest -V

    - name: Create source archives
      if: github.event_name == 'release'
      run: |
        mkdir -p artifacts
        tar -czvf artifacts/solver-source.tar.gz --exclude=".git" --exclude="build" .
        zip -r artifacts/solver-source.zip --exclude=".git/*" --exclude="build/*" .

    - name: Generate DEB package
      if: github.event_name == 'release'
      run: |
        cd build
        cpack -G DEB
        mv *.deb ../artifacts/

    - name: Generate RPM package
      if: github.event_name == 'release'
      run: |
        cd build
        cpack -G RPM
        mv *.rpm ../artifacts/

    - name: Upload artifacts to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
