name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Запуск при создании тега вида v1.0.0, v2.3.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake rpm

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest --output-on-failure

    - name: Create source tarball
      run: |
        mkdir -p artifacts
        tar -czvf artifacts/project-source.tar.gz --exclude=".git" --exclude="build" .

    - name: Generate DEB package
      run: |
        cd build
        cpack -G DEB
        mv *.deb ../artifacts/

    - name: Generate RPM package
      run: |
        cd build
        cpack -G RPM
        mv *.rpm ../artifacts/

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
