name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake rpm pkg-config

    - name: Configure CMake
      run: |
        cmake -B build -S . --debug-output 2>&1 | tee cmake.log
        if [ $? -ne 0 ]; then
          echo "===== CMake Error ====="
          cat cmake.log
          echo "===== CMakeLists.txt ====="
          cat CMakeLists.txt
          echo "===== Directory Structure ====="
          find . -type f -print
          exit 1
        fi

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: cd build && ctest -V

    - name: Create source tarball
      run: |
        mkdir -p artifacts
        tar -czvf artifacts/solver-source.tar.gz --exclude=".git" --exclude="build" .
        zip -r artifacts/solver-source.zip --exclude=".git/*" --exclude="build/*" .

    - name: Generate packages
      run: |
        cd build
        cpack -G DEB
        cpack -G RPM
        mv *.deb *.rpm ../artifacts/

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
